FROM tensorflow/tensorflow:2.3.0

RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN apt-get -y install jq

COPY . /opt/ml/code

# /opt/ml and all subdirectories are utilized by SageMaker
WORKDIR /opt/ml/code

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

ENV PATH="/opt/ml/code:${PATH}"



